// This file is generated by scripts/build-coa-library.mjs.
// Update the source report folders or mapping script, then regenerate it.

export type CoaDocument = {
  id: string;
  product: string;
  strength: string;
  format: "image" | "pdf";
  href: string;
  previewHref: string;
};

export const coaDocuments: CoaDocument[] = [
  {
    "id": "5-amino-1mq-01",
    "product": "5-Amino-1MQ",
    "strength": "10 mg",
    "format": "image",
    "href": "/coa/reports/5-amino-1mq/report-01.jpg",
    "previewHref": "/coa/reports/5-amino-1mq/report-01.jpg"
  },
  {
    "id": "5-amino-1mq-02",
    "product": "5-Amino-1MQ",
    "strength": "50 MG",
    "format": "image",
    "href": "/coa/reports/5-amino-1mq/report-02.jpg",
    "previewHref": "/coa/reports/5-amino-1mq/report-02.jpg"
  },
  {
    "id": "ahk-cu-01",
    "product": "AHK-Cu",
    "strength": "100 MG",
    "format": "image",
    "href": "/coa/reports/ahk-cu/report-01.jpg",
    "previewHref": "/coa/reports/ahk-cu/report-01.jpg"
  },
  {
    "id": "ahk-cu-02",
    "product": "AHK-Cu",
    "strength": "Analytical report",
    "format": "image",
    "href": "/coa/reports/ahk-cu/report-02.jpg",
    "previewHref": "/coa/reports/ahk-cu/report-02.jpg"
  },
  {
    "id": "aod-9604-01",
    "product": "AOD-9604",
    "strength": "5 MG",
    "format": "image",
    "href": "/coa/reports/aod-9604/report-01.jpg",
    "previewHref": "/coa/reports/aod-9604/report-01.jpg"
  },
  {
    "id": "aod-9604-02",
    "product": "AOD-9604",
    "strength": "5 MG",
    "format": "image",
    "href": "/coa/reports/aod-9604/report-02.jpg",
    "previewHref": "/coa/reports/aod-9604/report-02.jpg"
  },
  {
    "id": "bpc-157-01",
    "product": "BPC-157",
    "strength": "10 mg",
    "format": "image",
    "href": "/coa/reports/bpc-157/report-01.jpg",
    "previewHref": "/coa/reports/bpc-157/report-01.jpg"
  },
  {
    "id": "bpc-157-02",
    "product": "BPC-157",
    "strength": "10 MG",
    "format": "image",
    "href": "/coa/reports/bpc-157/report-02.jpeg",
    "previewHref": "/coa/reports/bpc-157/report-02.jpeg"
  },
  {
    "id": "bpc-157-03",
    "product": "BPC-157",
    "strength": "10 MG",
    "format": "image",
    "href": "/coa/reports/bpc-157/report-03.jpg",
    "previewHref": "/coa/reports/bpc-157/report-03.jpg"
  },
  {
    "id": "bpc-157-04",
    "product": "BPC-157",
    "strength": "10 MG",
    "format": "image",
    "href": "/coa/reports/bpc-157/report-04.webp",
    "previewHref": "/coa/reports/bpc-157/report-04.webp"
  },
  {
    "id": "bpc-157-05",
    "product": "BPC-157",
    "strength": "10 MG",
    "format": "image",
    "href": "/coa/reports/bpc-157/report-05.jpg",
    "previewHref": "/coa/reports/bpc-157/report-05.jpg"
  },
  {
    "id": "bpc-157-06",
    "product": "BPC-157",
    "strength": "10 MG",
    "format": "image",
    "href": "/coa/reports/bpc-157/report-06.jpg",
    "previewHref": "/coa/reports/bpc-157/report-06.jpg"
  },
  {
    "id": "bpc-157-07",
    "product": "BPC-157",
    "strength": "20 mg",
    "format": "image",
    "href": "/coa/reports/bpc-157/report-07.jpg",
    "previewHref": "/coa/reports/bpc-157/report-07.jpg"
  },
  {
    "id": "bpc-157-08",
    "product": "BPC-157",
    "strength": "5 MG",
    "format": "image",
    "href": "/coa/reports/bpc-157/report-08.jpg",
    "previewHref": "/coa/reports/bpc-157/report-08.jpg"
  },
  {
    "id": "bpc-157-plus-tb-500-01",
    "product": "BPC-157 + TB-500",
    "strength": "10 MG",
    "format": "image",
    "href": "/coa/reports/bpc-157-plus-tb-500/report-01.png",
    "previewHref": "/coa/reports/bpc-157-plus-tb-500/report-01.png"
  },
  {
    "id": "bpc-157-plus-tb-500-02",
    "product": "BPC-157 + TB-500",
    "strength": "10 MG",
    "format": "image",
    "href": "/coa/reports/bpc-157-plus-tb-500/report-02.png",
    "previewHref": "/coa/reports/bpc-157-plus-tb-500/report-02.png"
  },
  {
    "id": "bpc-157-plus-tb-500-03",
    "product": "BPC-157 + TB-500",
    "strength": "10 MG",
    "format": "image",
    "href": "/coa/reports/bpc-157-plus-tb-500/report-03.jpg",
    "previewHref": "/coa/reports/bpc-157-plus-tb-500/report-03.jpg"
  },
  {
    "id": "cagrilintide-01",
    "product": "Cagrilintide",
    "strength": "5 MG",
    "format": "image",
    "href": "/coa/reports/cagrilintide/report-01.jpg",
    "previewHref": "/coa/reports/cagrilintide/report-01.jpg"
  },
  {
    "id": "cjc-1295-plus-ipamorelin-01",
    "product": "CJC-1295 + Ipamorelin",
    "strength": "10 MG",
    "format": "image",
    "href": "/coa/reports/cjc-1295-plus-ipamorelin/report-01.jpg",
    "previewHref": "/coa/reports/cjc-1295-plus-ipamorelin/report-01.jpg"
  },
  {
    "id": "cjc-1295-plus-ipamorelin-02",
    "product": "CJC-1295 + Ipamorelin",
    "strength": "5 MG",
    "format": "image",
    "href": "/coa/reports/cjc-1295-plus-ipamorelin/report-02.jpg",
    "previewHref": "/coa/reports/cjc-1295-plus-ipamorelin/report-02.jpg"
  },
  {
    "id": "cjc-1295-plus-ipamorelin-03",
    "product": "CJC-1295 + Ipamorelin",
    "strength": "5 MG",
    "format": "image",
    "href": "/coa/reports/cjc-1295-plus-ipamorelin/report-03.jpeg",
    "previewHref": "/coa/reports/cjc-1295-plus-ipamorelin/report-03.jpeg"
  },
  {
    "id": "dsip-01",
    "product": "DSIP",
    "strength": "5 MG",
    "format": "image",
    "href": "/coa/reports/dsip/report-01.jpg",
    "previewHref": "/coa/reports/dsip/report-01.jpg"
  },
  {
    "id": "epithalon-01",
    "product": "Epithalon",
    "strength": "10 MG",
    "format": "image",
    "href": "/coa/reports/epithalon/report-01.jpg",
    "previewHref": "/coa/reports/epithalon/report-01.jpg"
  },
  {
    "id": "ghk-cu-01",
    "product": "GHK-Cu",
    "strength": "100 mg",
    "format": "image",
    "href": "/coa/reports/ghk-cu/report-01.jpg",
    "previewHref": "/coa/reports/ghk-cu/report-01.jpg"
  },
  {
    "id": "ghk-cu-02",
    "product": "GHK-Cu",
    "strength": "100 MG",
    "format": "image",
    "href": "/coa/reports/ghk-cu/report-02.jpg",
    "previewHref": "/coa/reports/ghk-cu/report-02.jpg"
  },
  {
    "id": "ghk-cu-03",
    "product": "GHK-Cu",
    "strength": "100 MG",
    "format": "image",
    "href": "/coa/reports/ghk-cu/report-03.jpg",
    "previewHref": "/coa/reports/ghk-cu/report-03.jpg"
  },
  {
    "id": "ghk-cu-04",
    "product": "GHK-Cu",
    "strength": "50 MG",
    "format": "image",
    "href": "/coa/reports/ghk-cu/report-04.jpeg",
    "previewHref": "/coa/reports/ghk-cu/report-04.jpeg"
  },
  {
    "id": "ghk-cu-05",
    "product": "GHK-Cu",
    "strength": "50 MG",
    "format": "image",
    "href": "/coa/reports/ghk-cu/report-05.jpg",
    "previewHref": "/coa/reports/ghk-cu/report-05.jpg"
  },
  {
    "id": "ghk-cu-06",
    "product": "GHK-Cu",
    "strength": "Raw material",
    "format": "image",
    "href": "/coa/reports/ghk-cu/report-06.jpg",
    "previewHref": "/coa/reports/ghk-cu/report-06.jpg"
  },
  {
    "id": "glp-2t-01",
    "product": "GLP-2T",
    "strength": "Analytical report",
    "format": "image",
    "href": "/coa/reports/glp-2t/report-01.jpeg",
    "previewHref": "/coa/reports/glp-2t/report-01.jpeg"
  },
  {
    "id": "glp-3rt-blend-01",
    "product": "GLP-3RT Blend",
    "strength": "30 MG",
    "format": "image",
    "href": "/coa/reports/glp-3rt-blend/report-01.jpg",
    "previewHref": "/coa/reports/glp-3rt-blend/report-01.jpg"
  },
  {
    "id": "glow-blend-01",
    "product": "Glow Blend",
    "strength": "50 MG + 10 MG",
    "format": "image",
    "href": "/coa/reports/glow-blend/report-01.jpeg",
    "previewHref": "/coa/reports/glow-blend/report-01.jpeg"
  },
  {
    "id": "glow-blend-02",
    "product": "Glow Blend",
    "strength": "Analytical report",
    "format": "image",
    "href": "/coa/reports/glow-blend/report-02.png",
    "previewHref": "/coa/reports/glow-blend/report-02.png"
  },
  {
    "id": "glow-blend-03",
    "product": "Glow Blend",
    "strength": "Blend report",
    "format": "image",
    "href": "/coa/reports/glow-blend/report-03.jpg",
    "previewHref": "/coa/reports/glow-blend/report-03.jpg"
  },
  {
    "id": "hcg-01",
    "product": "HCG",
    "strength": "10,000 IU",
    "format": "image",
    "href": "/coa/reports/hcg/report-01.webp",
    "previewHref": "/coa/reports/hcg/report-01.webp"
  },
  {
    "id": "hcg-02",
    "product": "HCG",
    "strength": "5000 IU",
    "format": "image",
    "href": "/coa/reports/hcg/report-02.webp",
    "previewHref": "/coa/reports/hcg/report-02.webp"
  },
  {
    "id": "hgh-somatropin-01",
    "product": "HGH / Somatropin",
    "strength": "15 IU",
    "format": "image",
    "href": "/coa/reports/hgh-somatropin/report-01.jpg",
    "previewHref": "/coa/reports/hgh-somatropin/report-01.jpg"
  },
  {
    "id": "hgh-somatropin-02",
    "product": "HGH / Somatropin",
    "strength": "Identity / purity report",
    "format": "pdf",
    "href": "/coa/reports/hgh-somatropin/report-02.pdf",
    "previewHref": "/coa/reports/hgh-somatropin/report-02-preview.png"
  },
  {
    "id": "igf-lr3-01",
    "product": "IGF-LR3",
    "strength": "1 MG",
    "format": "image",
    "href": "/coa/reports/igf-lr3/report-01.png",
    "previewHref": "/coa/reports/igf-lr3/report-01.png"
  },
  {
    "id": "ipamorelin-01",
    "product": "Ipamorelin",
    "strength": "10 MG",
    "format": "image",
    "href": "/coa/reports/ipamorelin/report-01.jpg",
    "previewHref": "/coa/reports/ipamorelin/report-01.jpg"
  },
  {
    "id": "ipamorelin-02",
    "product": "Ipamorelin",
    "strength": "10 MG",
    "format": "image",
    "href": "/coa/reports/ipamorelin/report-02.jpg",
    "previewHref": "/coa/reports/ipamorelin/report-02.jpg"
  },
  {
    "id": "klow-01",
    "product": "KLOW",
    "strength": "80 MG",
    "format": "image",
    "href": "/coa/reports/klow/report-01.jpg",
    "previewHref": "/coa/reports/klow/report-01.jpg"
  },
  {
    "id": "klow-02",
    "product": "KLOW",
    "strength": "80 MG",
    "format": "image",
    "href": "/coa/reports/klow/report-02.png",
    "previewHref": "/coa/reports/klow/report-02.png"
  },
  {
    "id": "klow-03",
    "product": "KLOW",
    "strength": "80 MG",
    "format": "image",
    "href": "/coa/reports/klow/report-03.jpg",
    "previewHref": "/coa/reports/klow/report-03.jpg"
  },
  {
    "id": "kpv-01",
    "product": "KPV",
    "strength": "10 MG",
    "format": "image",
    "href": "/coa/reports/kpv/report-01.png",
    "previewHref": "/coa/reports/kpv/report-01.png"
  },
  {
    "id": "kpv-02",
    "product": "KPV",
    "strength": "10 MG",
    "format": "image",
    "href": "/coa/reports/kpv/report-02.jpg",
    "previewHref": "/coa/reports/kpv/report-02.jpg"
  },
  {
    "id": "l-glutathione-01",
    "product": "L-Glutathione",
    "strength": "1500 MG",
    "format": "image",
    "href": "/coa/reports/l-glutathione/report-01.png",
    "previewHref": "/coa/reports/l-glutathione/report-01.png"
  },
  {
    "id": "melanotan-2-01",
    "product": "Melanotan-2",
    "strength": "Analytical report",
    "format": "image",
    "href": "/coa/reports/melanotan-2/report-01.png",
    "previewHref": "/coa/reports/melanotan-2/report-01.png"
  },
  {
    "id": "mots-c-01",
    "product": "MOTS-C",
    "strength": "10 MG",
    "format": "image",
    "href": "/coa/reports/mots-c/report-01.jpeg",
    "previewHref": "/coa/reports/mots-c/report-01.jpeg"
  },
  {
    "id": "mots-c-02",
    "product": "MOTS-C",
    "strength": "10 MG",
    "format": "image",
    "href": "/coa/reports/mots-c/report-02.jpg",
    "previewHref": "/coa/reports/mots-c/report-02.jpg"
  },
  {
    "id": "mots-c-03",
    "product": "MOTS-C",
    "strength": "10 MG",
    "format": "image",
    "href": "/coa/reports/mots-c/report-03.jpg",
    "previewHref": "/coa/reports/mots-c/report-03.jpg"
  },
  {
    "id": "mots-c-04",
    "product": "MOTS-C",
    "strength": "10 MG",
    "format": "image",
    "href": "/coa/reports/mots-c/report-04.jpg",
    "previewHref": "/coa/reports/mots-c/report-04.jpg"
  },
  {
    "id": "mots-c-05",
    "product": "MOTS-C",
    "strength": "10 MG",
    "format": "image",
    "href": "/coa/reports/mots-c/report-05.jpg",
    "previewHref": "/coa/reports/mots-c/report-05.jpg"
  },
  {
    "id": "mots-c-06",
    "product": "MOTS-C",
    "strength": "40 MG",
    "format": "image",
    "href": "/coa/reports/mots-c/report-06.jpg",
    "previewHref": "/coa/reports/mots-c/report-06.jpg"
  },
  {
    "id": "nad-plus-01",
    "product": "NAD+",
    "strength": "500 MG",
    "format": "image",
    "href": "/coa/reports/nad-plus/report-01.jpeg",
    "previewHref": "/coa/reports/nad-plus/report-01.jpeg"
  },
  {
    "id": "nad-plus-02",
    "product": "NAD+",
    "strength": "500 MG",
    "format": "image",
    "href": "/coa/reports/nad-plus/report-02.jpg",
    "previewHref": "/coa/reports/nad-plus/report-02.jpg"
  },
  {
    "id": "nad-plus-03",
    "product": "NAD+",
    "strength": "500 MG",
    "format": "image",
    "href": "/coa/reports/nad-plus/report-03.jpg",
    "previewHref": "/coa/reports/nad-plus/report-03.jpg"
  },
  {
    "id": "pt-141-01",
    "product": "PT-141",
    "strength": "10 MG",
    "format": "image",
    "href": "/coa/reports/pt-141/report-01.jpg",
    "previewHref": "/coa/reports/pt-141/report-01.jpg"
  },
  {
    "id": "pt-141-02",
    "product": "PT-141",
    "strength": "10 MG",
    "format": "image",
    "href": "/coa/reports/pt-141/report-02.png",
    "previewHref": "/coa/reports/pt-141/report-02.png"
  },
  {
    "id": "pt-141-03",
    "product": "PT-141",
    "strength": "Analytical report",
    "format": "image",
    "href": "/coa/reports/pt-141/report-03.jpg",
    "previewHref": "/coa/reports/pt-141/report-03.jpg"
  },
  {
    "id": "retatrutide-01",
    "product": "Retatrutide",
    "strength": "10 MG",
    "format": "image",
    "href": "/coa/reports/retatrutide/report-01.jpeg",
    "previewHref": "/coa/reports/retatrutide/report-01.jpeg"
  },
  {
    "id": "retatrutide-02",
    "product": "Retatrutide",
    "strength": "10 MG",
    "format": "image",
    "href": "/coa/reports/retatrutide/report-02.jpg",
    "previewHref": "/coa/reports/retatrutide/report-02.jpg"
  },
  {
    "id": "retatrutide-03",
    "product": "Retatrutide",
    "strength": "10 MG",
    "format": "image",
    "href": "/coa/reports/retatrutide/report-03.jpg",
    "previewHref": "/coa/reports/retatrutide/report-03.jpg"
  },
  {
    "id": "retatrutide-04",
    "product": "Retatrutide",
    "strength": "10 MG",
    "format": "image",
    "href": "/coa/reports/retatrutide/report-04.jpg",
    "previewHref": "/coa/reports/retatrutide/report-04.jpg"
  },
  {
    "id": "retatrutide-05",
    "product": "Retatrutide",
    "strength": "15 MG",
    "format": "image",
    "href": "/coa/reports/retatrutide/report-05.webp",
    "previewHref": "/coa/reports/retatrutide/report-05.webp"
  },
  {
    "id": "retatrutide-06",
    "product": "Retatrutide",
    "strength": "20 MG",
    "format": "image",
    "href": "/coa/reports/retatrutide/report-06.png",
    "previewHref": "/coa/reports/retatrutide/report-06.png"
  },
  {
    "id": "retatrutide-07",
    "product": "Retatrutide",
    "strength": "20 MG",
    "format": "image",
    "href": "/coa/reports/retatrutide/report-07.png",
    "previewHref": "/coa/reports/retatrutide/report-07.png"
  },
  {
    "id": "retatrutide-08",
    "product": "Retatrutide",
    "strength": "30 mg",
    "format": "image",
    "href": "/coa/reports/retatrutide/report-08.jpg",
    "previewHref": "/coa/reports/retatrutide/report-08.jpg"
  },
  {
    "id": "retatrutide-09",
    "product": "Retatrutide",
    "strength": "5 MG",
    "format": "image",
    "href": "/coa/reports/retatrutide/report-09.jpg",
    "previewHref": "/coa/reports/retatrutide/report-09.jpg"
  },
  {
    "id": "selank-01",
    "product": "Selank",
    "strength": "10 MG",
    "format": "image",
    "href": "/coa/reports/selank/report-01.jpg",
    "previewHref": "/coa/reports/selank/report-01.jpg"
  },
  {
    "id": "selank-02",
    "product": "Selank",
    "strength": "10 MG",
    "format": "image",
    "href": "/coa/reports/selank/report-02.jpeg",
    "previewHref": "/coa/reports/selank/report-02.jpeg"
  },
  {
    "id": "selank-03",
    "product": "Selank",
    "strength": "10 MG",
    "format": "image",
    "href": "/coa/reports/selank/report-03.jpg",
    "previewHref": "/coa/reports/selank/report-03.jpg"
  },
  {
    "id": "semaglutide-01",
    "product": "Semaglutide",
    "strength": "10 mg",
    "format": "image",
    "href": "/coa/reports/semaglutide/report-01.jpg",
    "previewHref": "/coa/reports/semaglutide/report-01.jpg"
  },
  {
    "id": "semaglutide-02",
    "product": "Semaglutide",
    "strength": "30 MG",
    "format": "image",
    "href": "/coa/reports/semaglutide/report-02.jpeg",
    "previewHref": "/coa/reports/semaglutide/report-02.jpeg"
  },
  {
    "id": "semaglutide-03",
    "product": "Semaglutide",
    "strength": "5 MG",
    "format": "image",
    "href": "/coa/reports/semaglutide/report-03.jpeg",
    "previewHref": "/coa/reports/semaglutide/report-03.jpeg"
  },
  {
    "id": "semaglutide-04",
    "product": "Semaglutide",
    "strength": "5 MG",
    "format": "image",
    "href": "/coa/reports/semaglutide/report-04.jpg",
    "previewHref": "/coa/reports/semaglutide/report-04.jpg"
  },
  {
    "id": "semax-01",
    "product": "Semax",
    "strength": "10 MG",
    "format": "image",
    "href": "/coa/reports/semax/report-01.jpg",
    "previewHref": "/coa/reports/semax/report-01.jpg"
  },
  {
    "id": "semax-02",
    "product": "Semax",
    "strength": "10 MG",
    "format": "image",
    "href": "/coa/reports/semax/report-02.png",
    "previewHref": "/coa/reports/semax/report-02.png"
  },
  {
    "id": "semax-03",
    "product": "Semax",
    "strength": "10 MG",
    "format": "image",
    "href": "/coa/reports/semax/report-03.webp",
    "previewHref": "/coa/reports/semax/report-03.webp"
  },
  {
    "id": "sermorelin-01",
    "product": "Sermorelin",
    "strength": "5 MG",
    "format": "image",
    "href": "/coa/reports/sermorelin/report-01.webp",
    "previewHref": "/coa/reports/sermorelin/report-01.webp"
  },
  {
    "id": "sermorelin-02",
    "product": "Sermorelin",
    "strength": "5 MG",
    "format": "image",
    "href": "/coa/reports/sermorelin/report-02.jpg",
    "previewHref": "/coa/reports/sermorelin/report-02.jpg"
  },
  {
    "id": "snap-8-01",
    "product": "SNAP-8",
    "strength": "100 MG",
    "format": "image",
    "href": "/coa/reports/snap-8/report-01.jpg",
    "previewHref": "/coa/reports/snap-8/report-01.jpg"
  },
  {
    "id": "ss-31-01",
    "product": "SS-31",
    "strength": "10 MG",
    "format": "image",
    "href": "/coa/reports/ss-31/report-01.jpg",
    "previewHref": "/coa/reports/ss-31/report-01.jpg"
  },
  {
    "id": "ss-31-02",
    "product": "SS-31",
    "strength": "50 MG",
    "format": "image",
    "href": "/coa/reports/ss-31/report-02.jpg",
    "previewHref": "/coa/reports/ss-31/report-02.jpg"
  },
  {
    "id": "tb-500-01",
    "product": "TB-500",
    "strength": "10 MG",
    "format": "image",
    "href": "/coa/reports/tb-500/report-01.png",
    "previewHref": "/coa/reports/tb-500/report-01.png"
  },
  {
    "id": "tb-500-02",
    "product": "TB-500",
    "strength": "10 MG",
    "format": "image",
    "href": "/coa/reports/tb-500/report-02.webp",
    "previewHref": "/coa/reports/tb-500/report-02.webp"
  },
  {
    "id": "tesamorelin-01",
    "product": "Tesamorelin",
    "strength": "10 MG",
    "format": "image",
    "href": "/coa/reports/tesamorelin/report-01.jpeg",
    "previewHref": "/coa/reports/tesamorelin/report-01.jpeg"
  },
  {
    "id": "tesamorelin-02",
    "product": "Tesamorelin",
    "strength": "10 MG",
    "format": "image",
    "href": "/coa/reports/tesamorelin/report-02.jpg",
    "previewHref": "/coa/reports/tesamorelin/report-02.jpg"
  },
  {
    "id": "tesamorelin-03",
    "product": "Tesamorelin",
    "strength": "10 MG",
    "format": "image",
    "href": "/coa/reports/tesamorelin/report-03.jpg",
    "previewHref": "/coa/reports/tesamorelin/report-03.jpg"
  },
  {
    "id": "thymosin-alpha-1-01",
    "product": "Thymosin Alpha-1",
    "strength": "10 MG",
    "format": "image",
    "href": "/coa/reports/thymosin-alpha-1/report-01.jpg",
    "previewHref": "/coa/reports/thymosin-alpha-1/report-01.jpg"
  },
  {
    "id": "thymosin-alpha-1-02",
    "product": "Thymosin Alpha-1",
    "strength": "10 MG",
    "format": "image",
    "href": "/coa/reports/thymosin-alpha-1/report-02.png",
    "previewHref": "/coa/reports/thymosin-alpha-1/report-02.png"
  },
  {
    "id": "thymosin-alpha-1-03",
    "product": "Thymosin Alpha-1",
    "strength": "5 MG",
    "format": "image",
    "href": "/coa/reports/thymosin-alpha-1/report-03.webp",
    "previewHref": "/coa/reports/thymosin-alpha-1/report-03.webp"
  },
  {
    "id": "thymosin-beta-4-01",
    "product": "Thymosin Beta-4",
    "strength": "10 MG",
    "format": "image",
    "href": "/coa/reports/thymosin-beta-4/report-01.jpg",
    "previewHref": "/coa/reports/thymosin-beta-4/report-01.jpg"
  },
  {
    "id": "tirzepatide-01",
    "product": "Tirzepatide",
    "strength": "10 MG",
    "format": "image",
    "href": "/coa/reports/tirzepatide/report-01.webp",
    "previewHref": "/coa/reports/tirzepatide/report-01.webp"
  },
  {
    "id": "tirzepatide-02",
    "product": "Tirzepatide",
    "strength": "15 MG",
    "format": "image",
    "href": "/coa/reports/tirzepatide/report-02.jpg",
    "previewHref": "/coa/reports/tirzepatide/report-02.jpg"
  },
  {
    "id": "tirzepatide-03",
    "product": "Tirzepatide",
    "strength": "30 mg",
    "format": "image",
    "href": "/coa/reports/tirzepatide/report-03.jpg",
    "previewHref": "/coa/reports/tirzepatide/report-03.jpg"
  },
  {
    "id": "tirzepatide-04",
    "product": "Tirzepatide",
    "strength": "30 MG",
    "format": "image",
    "href": "/coa/reports/tirzepatide/report-04.png",
    "previewHref": "/coa/reports/tirzepatide/report-04.png"
  },
  {
    "id": "tirzepatide-05",
    "product": "Tirzepatide",
    "strength": "30 MG",
    "format": "image",
    "href": "/coa/reports/tirzepatide/report-05.png",
    "previewHref": "/coa/reports/tirzepatide/report-05.png"
  },
  {
    "id": "tirzepatide-06",
    "product": "Tirzepatide",
    "strength": "30 MG",
    "format": "image",
    "href": "/coa/reports/tirzepatide/report-06.jpg",
    "previewHref": "/coa/reports/tirzepatide/report-06.jpg"
  },
  {
    "id": "tirzepatide-07",
    "product": "Tirzepatide",
    "strength": "60 MG",
    "format": "image",
    "href": "/coa/reports/tirzepatide/report-07.png",
    "previewHref": "/coa/reports/tirzepatide/report-07.png"
  },
  {
    "id": "tirzepatide-08",
    "product": "Tirzepatide",
    "strength": "60 MG",
    "format": "image",
    "href": "/coa/reports/tirzepatide/report-08.png",
    "previewHref": "/coa/reports/tirzepatide/report-08.png"
  }
];

export const coaProductOptions = [
  {
    "product": "5-Amino-1MQ",
    "count": 2
  },
  {
    "product": "AHK-Cu",
    "count": 2
  },
  {
    "product": "AOD-9604",
    "count": 2
  },
  {
    "product": "BPC-157",
    "count": 8
  },
  {
    "product": "BPC-157 + TB-500",
    "count": 3
  },
  {
    "product": "Cagrilintide",
    "count": 1
  },
  {
    "product": "CJC-1295 + Ipamorelin",
    "count": 3
  },
  {
    "product": "DSIP",
    "count": 1
  },
  {
    "product": "Epithalon",
    "count": 1
  },
  {
    "product": "GHK-Cu",
    "count": 6
  },
  {
    "product": "GLP-2T",
    "count": 1
  },
  {
    "product": "GLP-3RT Blend",
    "count": 1
  },
  {
    "product": "Glow Blend",
    "count": 3
  },
  {
    "product": "HCG",
    "count": 2
  },
  {
    "product": "HGH / Somatropin",
    "count": 2
  },
  {
    "product": "IGF-LR3",
    "count": 1
  },
  {
    "product": "Ipamorelin",
    "count": 2
  },
  {
    "product": "KLOW",
    "count": 3
  },
  {
    "product": "KPV",
    "count": 2
  },
  {
    "product": "L-Glutathione",
    "count": 1
  },
  {
    "product": "Melanotan-2",
    "count": 1
  },
  {
    "product": "MOTS-C",
    "count": 6
  },
  {
    "product": "NAD+",
    "count": 3
  },
  {
    "product": "PT-141",
    "count": 3
  },
  {
    "product": "Retatrutide",
    "count": 9
  },
  {
    "product": "Selank",
    "count": 3
  },
  {
    "product": "Semaglutide",
    "count": 4
  },
  {
    "product": "Semax",
    "count": 3
  },
  {
    "product": "Sermorelin",
    "count": 2
  },
  {
    "product": "SNAP-8",
    "count": 1
  },
  {
    "product": "SS-31",
    "count": 2
  },
  {
    "product": "TB-500",
    "count": 2
  },
  {
    "product": "Tesamorelin",
    "count": 3
  },
  {
    "product": "Thymosin Alpha-1",
    "count": 3
  },
  {
    "product": "Thymosin Beta-4",
    "count": 1
  },
  {
    "product": "Tirzepatide",
    "count": 8
  }
];
